ERROR 2022-07-22 17:41:57,106 - Error Message from Class of getSHA
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\test_plan_ui_origin_copy_1.py", line 737, in main
    tiggerList = self.gitLog()
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\test_plan_ui_origin_copy_1.py", line 698, in gitLog
    fullname = str(name[1])
IndexError: list index out of range
