ERROR 2022-07-15 18:28:58,924 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\oneTouch_tool\test_plan_ui.py", line 422, in get_list_item
    procress = subprocess.run([file_path, branch_input, SHA_input])
  File "C:\Program Files\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
  File "c:\Users\tinghao.chen\.vscode\extensions\ms-python.python-2022.10.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 853, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, cmd_line, *args)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
