ERROR 2022-07-07 10:33:56,488 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:/Tinghao.Chen/Desktop/oneTouch_tool/test_plan_ui.py", line 390, in get_list_item
    procress = subprocess.run([file_path, branch_input, SHA_input])
  File "C:\Program Files\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
ERROR 2022-07-07 10:34:03,573 - Error Message from get_list_item
Traceback (most recent call last):
  File "d:/Tinghao.Chen/Desktop/oneTouch_tool/test_plan_ui.py", line 390, in get_list_item
    procress = subprocess.run([file_path, branch_input, SHA_input])
  File "C:\Program Files\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。
